[project]
name = "login"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.2.0",
    "flask-wtf>=1.2.1",
    "flask>=3.0.3",
]
